Repository Coffect/coffect-BE, pull requests merged in 2025-07, with the labels that each got.

#18 feat : jwt생성로직, 미들웨어 추가
  .DS_Store
  .eslintrc.json
  @types/environment.d.ts
  @types/jwt.d.ts
  package-lock.json
  package.json
  src/.DS_Store
  src/config/token.ts
  src/index.ts
  src/middleware/verify.ts
  src/routes/tokentest.ts
  src/user/user.Message/user.Message.ts
  tsconfig.json
Labels: ✨Feature

#21 feat: tsoa 응답 통일, 에러 처리 미들웨어 #19
  @types/express.d.ts
  package.json
  src/config/swagger.json
  src/config/tsoaResponse.ts
  src/index.ts
  src/middleware/error.ts
  src/routes/tsoaRoutes.ts
  src/user/user.Controller/user.Controller.ts
  src/user/user.Message/user.Message.ts
Labels: ✨Feature

#23 feat:DB-Migration
  .eslintrc.json
  .github/ISSUE_TEMPLATE/기본_템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .prettierrc
  package-lock.json
  package.json
  prisma/migrations/20250709063516_coffect_0709/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/middleware/error.DTO/error.DTO.ts
  src/user/user.Controller/user.Controller.ts
  src/user/user.Message/user.Message.ts
  tsconfig.json
  tsoa.json
Labels: ✨Feature

#28 feat: add S3 setting
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/config/s3.ts
Labels: ✨Feature

#30 feat: db config setting
  package-lock.json
  package.json
  src/config/db.config.ts
Labels: ✨Feature

#32 Feat/seoki login
  .eslintrc.json
  package-lock.json
  package.json
  prisma/schema.prisma
  src/config/crypto.ts
  src/config/db.config.ts
  src/config/prisma.config.ts
  src/config/s3.ts
  src/config/swagger.json
  src/config/token.ts
  src/index.ts
  src/middleware/user.DTO/user.DTO.ts
  src/middleware/verifyJWT.ts
  src/routes/tokentest.ts
  src/routes/tsoaRoutes.ts
  src/user/user.Controller.ts
  src/user/user.Controller/user.Controller.ts
  src/user/user.Message.ts
  src/user/user.Model.ts
  src/user/user.Model/user.Model.ts
  src/user/user.Server/user.Server.ts
  src/user/user.Service.ts
  tsconfig.json
  tsoa.json
Labels: ✨Feature

#35 feat: postTodayInterest Index added & scheduler.ts added
  package-lock.json
  package.json
  prisma/migrations/20250712030008_coffect_0712/migration.sql
  prisma/schema.prisma
  src/coffeeChat/coffeeChat.Controller.ts
  src/coffeeChat/coffeeChat.Message.ts
  src/coffeeChat/coffeeChat.Model.ts
  src/coffeeChat/coffeeChat.Service.ts
  src/config/db.config.ts
  src/config/s3.ts
  src/config/scheduler.ts
  src/config/swagger.json
  src/routes/tsoaRoutes.ts
  tsoa.json
Labels: ✨Feature

#38 refactor: gitignore fixed - include swagger.json and tsoaRoutes.ts #37
  .gitignore
Labels: 🔨Refactoring

#40 feat/codie add thread
  src/config/swagger.json
  src/routes/tsoaRoutes.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Message.ts
  src/thread/thread.Model.ts
  src/thread/thread.Repository.ts
  src/thread/thread.Service.ts
  src/user/user.Controller.ts
Labels: ✨Feature

#48 feat : 회원가입 구현
  .gitignore
  .prettierrc
  prisma/schema.prisma
  src/coffeeChat/coffeeChat.Controller.ts
  src/coffeeChat/coffeeChat.Message.ts
  src/coffeeChat/coffeeChat.Model.ts
  src/coffeeChat/coffeeChat.Service.ts
  src/config/crypto.ts
  src/config/db.config.ts
  src/config/s3.ts
  src/config/scheduler.ts
  src/config/swagger.json
  src/config/tsoaResponse.ts
  src/middleware/error.DTO/error.DTO.ts
  src/middleware/error.ts
  src/middleware/univ.DTO/univ.DTO.ts
  src/middleware/upload.ts
  src/middleware/user.DTO/user.DTO.ts
  src/routes/tsoaRoutes.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Message.ts
  src/thread/thread.Model.ts
  src/thread/thread.Repository.ts
  src/thread/thread.Service.ts
  src/univ/univ.Controller.ts
  src/univ/univ.Message.ts
  src/univ/univ.Model.ts
  src/univ/univ.Service.ts
  src/user/user.Controller.ts
  src/user/user.Message.ts
  src/user/user.Model.ts
  src/user/user.Service.ts
Labels: ✨Feature

#52 fix: type Error fix
  src/coffeeChat/coffeeChat.Model.ts
  src/config/swagger.json
  src/routes/tsoaRoutes.ts
  src/thread/thread.Repository.ts
  src/user/user.Controller.ts
Labels: 🐛FIX

#60 feat:jun my page coffee chat
  prisma/schema.prisma
  src/coffeeChat/coffeeChat.Controller.ts
  src/coffeeChat/coffeeChat.Model.ts
  src/coffeeChat/coffeeChat.Service.ts
  src/config/swagger.json
  src/middleware/coffectChat.DTO/coffectChat.DTO.ts
  src/routes/tsoaRoutes.ts
Labels: ✨Feature

#64 fix/codie gitignore fix
  .eslintrc.json
  .github/ISSUE_TEMPLATE/기본_템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  src/config/swagger.json
  src/index.ts
  src/middleware/coffectChat.DTO/coffectChat.DTO.ts
  src/middleware/error.DTO/error.DTO.ts
  src/routes/tsoaRoutes.ts
  src/thread/thread.Service.ts
  tsconfig.json
  tsoa.json
Labels: 🐛FIX

#68 [feat] follow 로직 & feed 확인 로직 추가
  package.json
  src/coffeeChat/coffeeChat.Controller.ts
  src/follow/follow.Controller.ts
  src/follow/follow.Message.ts
  src/follow/follow.Model.ts
  src/follow/follow.Service.ts
  src/middleware/profile.DTO/profile.DTO.ts
  src/user/user.Controller.ts
Labels: ✨Feature

#74 [docs] swagger 문서 예시입력 추가
  package.json
  src/config/KSTtime.ts
  src/config/token.ts
  src/middleware/univ.DTO/univ.DTO.ts
  src/middleware/user.DTO/user.DTO.ts
  src/profile/profile.Controller.ts
  src/profile/profile.Service.ts
  src/univ/univ.Controller.ts
  src/user/user.Controller.ts
  src/user/user.Model.ts
Labels: 📝Docs

#83 fix: thread main type fix
  src/middleware/thread.DTO/thread.DTO.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Service.ts
Labels: 🐛FIX

#86 [feat] profile 관련 기능 구현
  src/config/s3.ts
  src/middleware/detailProfile.DTO/detailProfile.DTO.ts
  src/profile/profile.Controller.ts
  src/profile/profile.Model.ts
  src/profile/profile.Service.ts
  src/thread/thread.Model.ts
  src/thread/thread.Service.ts
  src/user/user.Controller.ts
  src/user/user.Model.ts
Labels: ✨Feature

#85 [feat] 게시글 수정, 삭제 API
  src/middleware/thread.DTO/thread.DTO.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Message.ts
  src/thread/thread.Model.ts
  src/thread/thread.Service.ts
Labels: ✨Feature

#88 [Feat] coffee chat api fixed
  src/coffeeChat/coffeeChat.Controller.ts
  src/coffeeChat/coffeeChat.Model.ts
  src/coffeeChat/coffeeChat.Service.ts
  src/config/scheduler.ts
  src/index.ts
  src/middleware/coffectChat.DTO/coffectChat.DTO.ts
Labels: 🐛FIX, ✨Feature

#90 [refactor] Profile 관심키워드 추가
  .vscode/settings.json
  prisma/schema.prisma
  src/coffeeChat/coffeeChat.Controller.ts
  src/middleware/detailProfile.DTO/detailProfile.DTO.ts
  src/profile/profile.Controller.ts
  src/profile/profile.Model.ts
  src/profile/profile.Service.ts
Labels: 🔨Refactoring

#92 [feat] 게시글 스크랩, 댓글, 이미지 업로드 API
  src/middleware/thread.DTO/thread.DTO.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Message.ts
  src/thread/thread.Model.ts
  src/thread/thread.Service.ts
Labels: ✨Feature

#94 [refac] middleWare to Security Changed && currentCardRecommend fixed
  src/coffeeChat/coffeeChat.Controller.ts
  src/coffeeChat/coffeeChat.Service.ts
  src/follow/follow.Controller.ts
Labels: 🔨Refactoring

#101 [refactor] tsoa validation 에러 핸들링 추가
  src/middleware/error.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Model.ts
  src/thread/thread.Service.ts
Labels: 🔨Refactoring

#102 feat : profile id 값 추가
  src/middleware/detailProfile.DTO/detailProfile.DTO.ts
  src/profile/profile.Model.ts
Labels: ✨Feature
