Repository Coffect/coffect-BE, pull requests merged in 2025-08, with the labels that each got.

#125 [refactor] 게시글 메인 화면 API 개선
  src/middleware/detailProfile.DTO/detailProfile.DTO.ts
  src/middleware/thread.DTO/thread.DTO.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Model.ts
  src/thread/thread.Service.ts
Labels: 🔨Refactoring

#131 [feat] 유저 시간표 관련 api
  prisma/schema.prisma
  src/profile/profile.Controller.ts
  src/profile/profile.Message.ts
  src/profile/profile.Model.ts
  src/profile/profile.Service.ts
Labels: ✨Feature

#133 [feat] Alert function added
  package-lock.json
  package.json
  prisma/schema.prisma
  src/alert/alert.Controller.ts
  src/alert/alert.Message.ts
  src/alert/alert.Model.ts
  src/alert/alert.Service.ts
  src/coffeeChat/coffeeChat.Model.ts
  src/coffeeChat/coffeeChat.Service.ts
  src/config/fcm.ts
  src/user/user.Controller.ts
  src/user/user.Service.ts
Labels: ✨Feature

#144 [feat] Socket 통신 기본 세팅
  package-lock.json
  package.json
  src/coffeeChat/coffeeChat.Controller.ts
  src/follow/follow.Controller.ts
  src/index.ts
  src/middleware/verifyJWT.ts
  src/middleware/verifySocket.ts
  src/socket/socket.model.ts
  src/socket/socket.service.ts
  src/socket/socket.ts
Labels: ✨Feature

#148 [refactor] 게시글 이미지 업로드 플로우 수정
  src/middleware/thread.DTO/thread.DTO.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Model.ts
  src/thread/thread.Service.ts
Labels: 🔨Refactoring

#149 [feat] 채팅방 기능 추가
  prisma/mongodb/schema.prisma
  prisma/mysql/schema.prisma
  src/chat/chat.Controller.ts
  src/chat/chat.Message.ts
  src/chat/chat.Model.ts
  src/chat/chat.Service.ts
  src/middleware/chat.DTO/chat.DTO.ts
  src/socket/socket.model.ts
  src/socket/socket.service.ts
  src/socket/socket.ts
  src/thread/mongotest.Controller.ts
Labels: ✨Feature

#195 [feat] 채팅 읽기 api
  src/chat/chat.Controller.ts
  src/chat/chat.Model.ts
  src/chat/chat.Service.ts
Labels: ✨Feature

#198 [refactor] profile/id 기능 복구
  src/profile/profile.Controller.ts
  src/profile/profile.Service.ts
Labels: 🔨Refactoring

#199 [feat] photo upload in chat room
  src/chat/chat.Controller.ts
  src/chat/chat.Model.ts
  src/chat/chat.Service.ts
  src/socket/socket.message.ts
Labels: ✨Feature

#202 [fix] image upload
  src/chat/chat.Controller.ts
  src/chat/chat.Model.ts
  src/chat/chat.Service.ts
Labels: 🐛FIX

#208 Fix/codie thread image
  prisma/mysql/schema.prisma
  src/middleware/thread.DTO/thread.DTO.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Model.ts
  src/thread/thread.Service.ts
Labels: 🐛FIX

#216 fix:lookup typo fix
  src/middleware/univ.DTO/univ.DTO.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Service.ts
Labels: 🐛FIX

#226 [fix] 이미지 없이 게시글 업로드
  src/thread/thread.Controller.ts
Labels: 🐛FIX

#231 [feat] coffeechat 보여주기
  src/coffeeChat/coffeeChat.Controller.ts
  src/coffeeChat/coffeeChat.Model.ts
  src/coffeeChat/coffeeChat.Service.ts
  src/config/fcm.ts
  src/middleware/coffectChat.DTO/coffectChat.DTO.ts
  src/user/user.Model.ts
  src/user/user.Service.ts
Labels: ✨Feature

#238 [refac] FCM 포맷 변경
  prisma/mysql/schema.prisma
  src/config/fcm.ts
Labels: 🔨Refactoring

#247 refactor: contain additional info
  src/middleware/thread.DTO/thread.DTO.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Model.ts
  src/thread/thread.Service.ts
Labels: 🔨Refactoring

#259 refactor: 댓글에 학과 추가
  src/middleware/thread.DTO/thread.DTO.ts
  src/thread/thread.Model.ts
Labels: 🔨Refactoring

#260 [refactor]: 쓰레드 스크랩, 프로토콜 수정
  src/middleware/thread.DTO/thread.DTO.ts
  src/profile/profile.Controller.ts
  src/profile/profile.Model.ts
Labels: 🔨Refactoring

#261 fix : FCM 허용 안해도 로그아웃되도록 구현
  src/profile/profile.Service.ts
  src/user/user.Model.ts
  src/user/user.Service.ts
Labels: 🐛FIX

#263 refacor : 쓰레드 조회 추가
  src/profile/profile.Model.ts
Labels: 🔨Refactoring

#265 refactor : 진짜 고침
  src/profile/profile.Controller.ts
  src/profile/profile.Model.ts
  src/profile/profile.Service.ts
Labels: 🐛FIX

#264 fix: 유저 시간표 기본 업로드
  src/profile/profile.Controller.ts
  src/user/user.Model.ts
Labels: 🐛FIX

#272 feat : websocket 변경
  src/index.ts
Labels: ✨Feature

#273 refactor : 회원가입시 기본 질문리스트 추가
  src/config/fcm.ts
  src/profile/profile.Model.ts
  src/user/user.Model.ts
Labels: 🔨Refactoring

#275 [feat] follower following add
  src/follow/follow.Controller.ts
  src/follow/follow.Model.ts
  src/follow/follow.Service.ts
  src/middleware/follow.DTO/follow.DTO.ts
Labels: ✨Feature

#282 Feat/codie bylikes
  src/coffeeChat/coffeeChat.Controller.ts
  src/coffeeChat/coffeeChat.Message.ts
  src/coffeeChat/coffeeChat.Model.ts
  src/config/fcm.ts
Labels: ✨Feature

#287 fix: image send socket fix
  src/chat/chat.Controller.ts
  src/chat/chat.Model.ts
  src/chat/chat.Service.ts
  src/middleware/socket.DTO/socket.DTO.ts
  src/socket/socket.ts
Labels: 🐛FIX

#292 fix: tostring 수정
  src/socket/socket.ts
Labels: 🐛FIX

#297 [fix] Chat Api UTF time
  src/chat/chat.Model.ts
Labels: 🐛FIX

#301 feat: thread/main api에 인기순 조회 추가
  src/middleware/thread.DTO/thread.DTO.ts
  src/middleware/univ.DTO/univ.DTO.ts
  src/thread/thread.Controller.ts
  src/thread/thread.Service.ts
Labels: ✨Feature
